name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

permissions:
  contents: read

jobs:
  test-qe:
    name: QE smoke test (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # make package importable (even if not strictly needed for tools/)
          pip install -e .

      - name: Run QE smoke (fast)
        run: |
          python tools/press_start_qe.py --out runs/qe_ci --events 5000

      - name: Upload QE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qe-smoke-artifacts
          path: |
            runs/qe_ci/*.png
            runs/qe_ci/*.csv
          if-no-files-found: warn

  build-paper:
    name: Build LaTeX paper (Linux)
    runs-on: ubuntu-latest
    needs: test-qe

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install TeX Live (minimal set for latexmk/pdf)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            latexmk texlive-latex-recommended texlive-latex-extra \
            texlive-fonts-recommended texlive-fonts-extra texlive-science

      - name: Build PDF
        run: |
          # If your main .tex file has a different name, change it here:
          latexmk -pdf -interaction=nonstopmode -halt-on-error Advanced_Waves_and_Retrocausality.tex

      - name: Upload paper PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: Advanced_Waves_and_Retrocausality.pdf
          if-no-files-found: error
