name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: smoke (${{ matrix.os }} / py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements.txt

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package + minimal deps
        run: |
          pip install -e .
          pip install numpy pandas matplotlib scipy pyyaml

      - name: Print version
        run: |
          python - << 'PY'
import sys
try:
    import timesym
    ver = getattr(timesym, "__version__", "unknown")
except Exception as e:
    ver = f"import failed: {e}"
print("Python:", sys.version)
print("timesym version:", ver)
PY

      - name: Run QE smoke (fast, cross-platform)
        run: |
          python tools/press_start_qe.py --out runs/ci_smoke --events 1000

      - name: Upload QE artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qe-smoke-${{ matrix.os }}
          path: runs/ci_smoke/**/*
          if-no-files-found: ignore

  paper:
    name: build paper (ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install TeX (minimal set for article class + extras)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended \
            texlive-science texlive-binaries latexmk

      - name: Build PDF
        # Adjust filename/path below if your .tex is elsewhere
        run: |
          latexmk -pdf -halt-on-error -interaction=nonstopmode Advanced_Waves_and_Retrocausality.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: Advanced_Waves_and_Retrocausality.pdf
          if-no-files-found: error
