name: CI (sim smoke tests only)

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]
  pull_request:

permissions:
  contents: read

jobs:
  sims:
    name: Run simulation smoke tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip
          # install your package (and its deps if listed in pyproject)
          pip install -e .
          # safety net if not all deps are in pyproject
          pip install numpy scipy pandas matplotlib pyyaml arviz

      - name: QE smoke (fast)
        run: |
          python tools/press_start_qe.py --out runs/qe_ci --events 5000

      - name: RF smoke (simulate)
        run: |
          python final_analysis.py --simulate --out runs/cable_ci --Vpp 1.0

      - name: Optical smoke (simulate)
        run: |
          python final_analysis_optical.py --simulate --out runs/optical_ci

      - name: Upload run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: runs-${{ runner.os }}
          path: runs/**
          if-no-files-found: warn
